// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get the current app configuration.
 */
async getConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the app configuration.
 * SRP: Uses ConfigChangeHandler trait for change detection and response.
 */
async saveConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get transcription history.
 */
async getHistory(limit: number | null) : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new history entry.
 */
async addHistoryEntry(text: string, language: string | null, duration: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_history_entry", { text, language, duration }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all history entries.
 */
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a history entry by ID.
 */
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search history.
 */
async searchHistory(query: string, limit: number | null) : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history", { query, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all dictionary entries.
 */
async getDictionary() : Promise<Result<DictionaryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new dictionary entry.
 */
async addDictionaryEntry(source: string, replacement: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_dictionary_entry", { source, replacement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a dictionary entry by id (line index).
 */
async deleteDictionaryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a dictionary entry by id (line index).
 */
async updateDictionaryEntry(id: number, source: string, replacement: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary_entry", { id, source, replacement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get recent debug entries.
 */
async getDebugEntries(limit: number | null) : Promise<Result<DebugEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_debug_entries", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all debug files.
 */
async clearDebug() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_debug") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get debug directory path.
 */
async getDebugDir() : Promise<string> {
    return await TAURI_INVOKE("get_debug_dir");
},
/**
 * Switch the overlay theme at runtime by emitting `overlay://theme`.
 * 
 * Effect:
 * - the overlay webview's `useOverlayState` listener pulls `themeId`
 * from the payload → `useFetchedHandyTheme` re-fetches → the
 * `HandyThemeProvider` republishes 19 CSS variables on `:root`
 * → the pill repaints in the new palette + animation timings.
 * 
 * Does NOT persist to config.db, so the user's stored preference is
 * preserved.
 */
async debugSetHandyTheme(themeId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_set_handy_theme", { themeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force the overlay into a specific {@link OverlayState} mode by
 * emitting `overlay://state`. Bypasses orchestrator gating so test
 * suites can capture every visual state (idle / recording /
 * transcribing / error) without driving real audio.
 */
async debugSetOverlayState(state: OverlayState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_set_overlay_state", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inject synthetic spectrum bins into the overlay (e.g. simulate a
 * loud burst for peak-decay screenshots).
 * 
 * `bins` must have exactly `crate::audio::SPECTRUM_BARS` entries
 * (currently 32) or the command returns an error.
 */
async debugEmitSpectrum(bins: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_emit_spectrum", { bins }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sugar over [`debug_emit_spectrum`] with all zeros — makes the bars
 * fall back to the configured peak-decay rate so a slow theme like
 * `quiet_reed` (peak_decay=0.95) keeps high bars visible while `neon`
 * (peak_decay=0.70) drops them fast.
 */
async debugEmitSilence() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_emit_silence") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all failed transcriptions.
 */
async getFailedTranscriptions() : Promise<Result<FailedTranscription[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_failed_transcriptions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismiss (remove) a failed transcription by ID.
 */
async dismissFailedTranscription(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_failed_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retry a failed transcription.
 * 
 * Loads the audio from storage, runs transcription again with current config,
 * and on success adds the result to history and removes from failed storage.
 */
async retryTranscription(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check all required permissions and return their status.
 */
async checkPermissions() : Promise<PermissionInfo[]> {
    return await TAURI_INVOKE("check_permissions");
},
/**
 * Open system settings for a specific permission.
 */
async openPermissionSettings(permission: string) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { permission });
},
/**
 * Request microphone permission (triggers system dialog on macOS).
 * This is needed for the app to appear in Privacy > Microphone list.
 * Uses AVFoundation via osascript to safely trigger permission dialog without crash.
 */
async requestMicrophonePermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_microphone_permission");
},
/**
 * Request accessibility permission (triggers system dialog on macOS).
 * This is needed for auto-typing functionality.
 * Uses System Events via osascript to safely trigger permission dialog.
 */
async requestAccessibilityPermission() : Promise<boolean> {
    return await TAURI_INVOKE("request_accessibility_permission");
},
/**
 * Restart the application to apply permission changes.
 * macOS requires restart for Accessibility and Input Monitoring permissions
 * to take effect (TCC loads permissions at process start).
 */
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
},
/**
 * Bring the app window to the front.
 * Useful after returning from System Settings.
 */
async bringToFront() : Promise<void> {
    await TAURI_INVOKE("bring_to_front");
},
/**
 * Get all LLM providers.
 */
async getLlmProviders() : Promise<Result<LlmProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_llm_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new LLM provider.
 */
async addLlmProvider(provider: LlmProvider) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_llm_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an LLM provider (only non-builtin).
 */
async removeLlmProvider(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_llm_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing LLM provider.
 */
async updateLlmProvider(provider: LlmProvider) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_llm_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLlmPrompts() : Promise<Result<LlmPrompt[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_llm_prompts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createLlmPrompt(id: string, name: string, prompt: string) : Promise<Result<LlmPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_llm_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateLlmPrompt(id: string, name: string, prompt: string) : Promise<Result<LlmPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_llm_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLlmPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_llm_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveLlmPromptId() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_llm_prompt_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveLlmPromptId(id: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_llm_prompt_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listShortcutBindings() : Promise<Result<ShortcutBinding[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_shortcut_bindings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateShortcutBinding(id: string, newCombo: string) : Promise<Result<ShortcutBinding, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_shortcut_binding", { id, newCombo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetShortcutBinding(id: string) : Promise<Result<ShortcutBinding, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_shortcut_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isFirstRun() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_first_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markFirstRunComplete() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_first_run_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show the overlay window with the given state.
 */
async showOverlay(state: OverlayState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_overlay", { state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the overlay window.
 */
async hideOverlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the overlay position.
 */
async updateOverlayPosition(position: OverlayPosition, margin: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_overlay_position", { position, margin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current overlay state (pull-based initialization).
 * Frontend calls this after setting up listeners to get missed state.
 */
async getOverlayState() : Promise<OverlayState> {
    return await TAURI_INVOKE("get_overlay_state");
},
/**
 * Get the currently configured overlay theme id (pull-after-subscribe).
 * Frontend calls this after subscribing to overlay://theme so it never
 * misses the initial event if it fired before the webview JS was ready.
 */
async getCurrentOverlayTheme() : Promise<string> {
    return await TAURI_INVOKE("get_current_overlay_theme");
},
/**
 * Get all available visualization themes.
 * NOTE: this command reads from the *user* config themes dir (seeded by
 * Task 4.3 at startup). If seeding hasn't run yet (e.g. first launch before
 * Task 4.3 is merged), the list will be empty. No fallback hack — ordering
 * dependency is intentional.
 * 
 * Returns an error if theme scanning fails (e.g. themes dir is a file instead
 * of a directory). The frontend must surface this so the user sees a
 * concrete problem instead of a silently-empty dropdown.
 */
async getVisualizationThemes() : Promise<Result<ThemeInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_visualization_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a visualization theme.
 */
async validateVisualizationTheme(themeId: string) : Promise<ThemeTestResult> {
    return await TAURI_INVOKE("validate_visualization_theme", { themeId });
},
/**
 * Get path to themes directory.
 */
async getThemesDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_themes_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a builtin theme to a theme folder for user customization.
 */
async exportBuiltinTheme(themeId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_builtin_theme", { themeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload visualization themes from disk.
 */
async reloadVisualizationThemes() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_visualization_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview a visualization theme without saving config.
 */
async previewVisualizationTheme(themeId: string, reloadFromDisk: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_visualization_theme", { themeId, reloadFromDisk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the entry script source for a theme id.
 */
async readThemeScript(themeId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_theme_script", { themeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the manifest (params included) for a theme id.
 */
async getThemeManifest(themeId: string) : Promise<ThemeManifest | null> {
    return await TAURI_INVOKE("get_theme_manifest", { themeId });
},
/**
 * Diagnostic command — lets the overlay webview log a marker to the Rust
 * tracing stream. Used during E2E development to verify that the React
 * app inside the NSPanel actually runs and receives state events.
 */
async debugLogOverlay(message: string) : Promise<void> {
    await TAURI_INVOKE("debug_log_overlay", { message });
},
/**
 * Diagnostic command — injects arbitrary JS into the overlay panel webview
 * via `WebviewWindow::eval`. This bypasses the Tauri event bus and lets us
 * verify whether the panel's JS execution context is alive at all.
 * 
 * The injected script is expected to call back into the host via
 * `__TAURI_INTERNALS__.invoke('debug_log_overlay', { message })`. If we see
 * the corresponding `overlay-diag` log line, JS is running. If not, the
 * panel webview is silent.
 */
async debugEvalOverlay(script: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_eval_overlay", { script }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available audio input devices.
 * Requires microphone permission to access audio hardware.
 */
async listAudioDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start audio recording.
 * Requires microphone permission to access audio hardware.
 */
async startRecording(deviceId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop recording and return audio data.
 */
async stopRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current recording status.
 */
async getRecordingStatus() : Promise<boolean> {
    return await TAURI_INVOKE("get_recording_status");
},
/**
 * Get current audio level (0-100).
 */
async getAudioLevel() : Promise<number> {
    return await TAURI_INVOKE("get_audio_level");
},
/**
 * Get FFT spectrum bins for visualization (32 frequency magnitudes, 0.0-1.0).
 * Returns empty array if not recording or not enough samples.
 */
async getSpectrumBins() : Promise<number[]> {
    return await TAURI_INVOKE("get_spectrum_bins");
},
/**
 * Transcribe pending audio using Groq API.
 */
async transcribeAudio(apiKey: string, model: string | null, language: string | null) : Promise<Result<TranscriptionResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { apiKey, model, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy text to clipboard.
 */
async copyToClipboard(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_to_clipboard", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Auto-type text.
 */
async typeText(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("type_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manual start recording (for UI button).
 */
async manualStartRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_start_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manual stop recording (for UI button).
 */
async manualStopRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel any in-progress recording (Handy-style overlay cancel button).
 * Has no effect while transcription is already in flight.
 */
async cancelOperation() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_operation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all pending suggestions.
 */
async getPendingSuggestions() : Promise<Result<PendingSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pending_suggestions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get count of pending suggestions.
 */
async getPendingCount() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pending_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a pending suggestion and add to dictionary.
 */
async approveSuggestion(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_suggestion", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve a suggestion by source and replacement.
 */
async approveSuggestionBySource(source: string, replacement: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("approve_suggestion_by_source", { source, replacement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject a pending suggestion.
 */
async rejectSuggestion(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_suggestion", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject a suggestion by source and replacement.
 */
async rejectSuggestionBySource(source: string, replacement: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reject_suggestion_by_source", { source, replacement }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reprocess history entries through LLM to generate suggestions.
 */
async reprocessHistoryForSuggestions(limit: number | null) : Promise<Result<ReprocessResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reprocess_history_for_suggestions", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Main application configuration.
 * 
 * Groups:
 * - vad: Voice Activity Detection settings
 * - overlay: Recording overlay UI settings
 * - llm: LLM post-processing settings
 * - dictionary: Dictionary and learning settings
 */
export type AppConfig = { api_key?: string; model?: string; language?: string; hotkey?: string; 
/**
 * Minimum hold time (ms) before the hotkey activates. Presses
 * shorter than this are ignored — allows AltGr/Ctrl to keep working
 * as a key modifier for combinations.
 */
hotkey_hold_ms?: number; 
/**
 * Minimum captured-audio duration (ms, after VAD) below which a
 * recording is dropped without hitting the API. See
 * `DEFAULT_MIN_RECORDING_MS`.
 */
min_recording_ms?: number; auto_type?: boolean; auto_enter?: boolean; typing_delay?: number; notifications?: boolean; backend?: string; debug?: boolean; audio_device?: string; history_enabled?: boolean; history_days?: number; active_provider?: string; cloud_provider?: string; local_backend?: string; text_processing?: boolean; 
/**
 * Append a single trailing space to the output (after dictionary +
 * hallucination filter + optional LLM post-process). Prevents
 * successive dictations from merging into one another. Idempotent
 * if the text already ends in whitespace. See
 * `output::format_output_text` for the actual transformation.
 */
append_trailing_space?: boolean; 
/**
 * When `true`, request Whisper to translate the audio to English
 * (`task=translate` on Groq / OpenAI Whisper). Useful for bilingual
 * users: speak Russian, get English in the clipboard. Honoured by
 * the transcription client at request-build time.
 */
translate_to_english?: boolean; 
/**
 * Auto-submit key combo emitted at the end of the output pipeline.
 * `Off` = no extra keystroke (default). `Enter` / `CmdEnter` /
 * `ShiftEnter` press the chord so chat clients (Slack, Telegram,
 * ChatGPT, etc.) send the typed message without the user touching
 * the keyboard. See `output::auto_submit`.
 */
auto_submit_key?: AutoSubmitKey; 
/**
 * Audio feedback beeps on recording start / stop / error.
 * Off by default. See `audio_feedback`.
 */
audio_feedback?: AudioFeedbackSettings; 
/**
 * Multi-binding shortcut list (#2). Lives in config alongside the
 * legacy single `hotkey` string so callers can opt in gradually.
 * Empty by default — fresh installs go through
 * `storage::shortcut_bindings_sqlite::seed_defaults_if_empty()`
 * (T-B2.3) on first run.
 */
shortcut_bindings?: ShortcutBinding[]; 
/**
 * `true` once the user has completed the onboarding flow (#10).
 * The frontend gates `/onboarding` redirect on this flag.
 */
first_run_completed?: boolean; 
/**
 * Hotkey activation mode (#3):
 * 'hold'   — record while hotkey held, stop on release (legacy).
 * 'toggle' — tap to start, tap again to stop.
 * Stored as a string for forward-compat; unrecognized values
 * default to 'hold'.
 */
hotkey_mode?: string; 
/**
 * Recording history retention policy (#5):
 * 'never' | 'preserve_limit' | 'days_3' | 'weeks_2' | 'months_3'.
 * 'never' (default) preserves all entries forever. The cleanup
 * task runs on app startup once per launch.
 */
retention_period?: string; 
/**
 * How many recent entries `retention_period = preserve_limit`
 * should keep. Ignored for other policies.
 */
retention_limit?: number; 
/**
 * Always-on microphone (#8). When enabled, the capture stream
 * stays warm between recordings so the first sample reaches the
 * buffer with zero cold-start delay.
 * 
 * **Platform behaviour**:
 * - macOS: the audio thread already implements pause/resume
 * (see `recorder::stop_macos_pause`) so the stream is
 * effectively always-on regardless of this flag — we surface
 * the toggle for UX parity with Linux/Windows and for the
 * privacy notice.
 * - Linux/Windows: TODO — currently the cpal stream is dropped
 * on `stop()`. Wiring is left for a follow-up commit; the
 * flag is honoured in the config schema today.
 */
always_on_microphone?: boolean; paste_shortcuts?: string; api_url_override?: string | null; vad?: VadConfig; overlay?: OverlayConfig; llm?: LlmConfig; dictionary?: DictionaryConfig }
/**
 * Audio device info for UI display.
 */
export type AudioDevice = { id: string; name: string; is_default: boolean }
/**
 * User-facing settings for the audio feedback feature. Live in
 * `AppConfig` (added in T-B6.3 wiring) and flow through to `play()`.
 */
export type AudioFeedbackSettings = { enabled: boolean; 
/**
 * Linear volume in [0.0, 1.0]. Values outside that range are
 * clamped at call time \u2014 see `clamp_volume`.
 */
volume: number }
/**
 * Which key combo to fire after typing. `Off` skips entirely \u2014 this
 * is the safe default for users who don't want their messages
 * auto-sent.
 */
export type AutoSubmitKey = "off" | "enter" | "cmd_enter" | "shift_enter"
/**
 * Debug log entry for a single recording session.
 */
export type DebugEntry = { timestamp: string; audio_file: string | null; audio_size_bytes: number; transcription: TranscriptionLog | null; llm: LlmLog | null }
/**
 * Dictionary and learning settings.
 */
export type DictionaryConfig = { path?: string; learning_mode?: string; learning_threshold?: number }
/**
 * Dictionary entry for frontend display.
 */
export type DictionaryEntry = { id: number; source: string; replacement: string }
/**
 * Metadata for a failed transcription attempt.
 */
export type FailedTranscription = { 
/**
 * Unique identifier (e.g., "001", "002", "003")
 */
id: string; 
/**
 * Error message that caused the failure
 */
error: string; 
/**
 * Partial Whisper transcription text (if any)
 */
whisper_text: string | null; 
/**
 * Timestamp when the failure occurred
 */
timestamp: string; 
/**
 * Provider that was used (e.g., "groq", "openai")
 */
provider: string }
/**
 * History entry for frontend display.
 */
export type HistoryEntry = { id: number; timestamp: string; text: string; language: string | null; duration: number | null }
/**
 * LLM post-processing settings.
 */
export type LlmConfig = { enabled?: boolean; provider?: string; api_url?: string; api_key?: string; model?: string; prompt?: string }
/**
 * LLM debug info.
 */
export type LlmLog = { provider: string; model: string; prompt: string; input_text: string; output_text: string; duration_ms: number }
/**
 * A model available for an LLM provider.
 */
export type LlmModel = { id: string; name: string }
/**
 * A single named LLM prompt template. `id` is the stable string key
 * used by the rest of the system (config selection, SQLite primary
 * key). `name` is the human-readable label rendered in the UI.
 */
export type LlmPrompt = { id: string; name: string; prompt: string }
/**
 * An LLM provider configuration.
 */
export type LlmProvider = { id: string; name: string; api_url: string; models: LlmModel[]; default_model: string; builtin?: boolean }
/**
 * Recording overlay settings.
 */
export type OverlayConfig = { enabled?: boolean; position?: string; size?: string; 
/**
 * Margin from screen edge in pixels. Can be negative to move overlay off-screen.
 */
margin?: number; 
/**
 * Audio level multiplier for waveform visualization (100-1000).
 * Higher = more sensitive for quiet microphones.
 */
audio_boost?: number; 
/**
 * Visualization theme name.
 */
theme?: string; 
/**
 * Overlay backend: `"auto"` (default, picks best), `"native"`, `"subprocess"`,
 * `"nspanel"` (macOS only, opt-in), or `"none"`.
 */
backend?: string }
/**
 * Overlay position on screen.
 */
export type OverlayPosition = "bottom_left" | "bottom_right" | "top_left" | "top_right" | "center" | "top_center" | "bottom_center" | "left_center" | "right_center"
export type OverlayState = "hidden" | "idle" | "recording" | "transcribing" | { queued: number }
/**
 * Overlay state for display.
 */
export type OverlayState = "hidden" | "idle" | "recording" | "transcribing" | { error: string }
/**
 * Pending suggestion entry for frontend display.
 */
export type PendingSuggestion = { id: number; source: string; replacement: string; count: number; first_seen: string; last_seen: string }
/**
 * Permission status response for frontend.
 */
export type PermissionInfo = { name: string; status: string; description: string }
/**
 * Result of reprocessing history through LLM.
 */
export type ReprocessResult = { processed: number; suggestions_found: number }
/**
 * What the orchestrator should do when this binding fires.
 * 
 * `Transcribe` is the legacy behaviour: record, transcribe, paste.
 * `TranscribePostProcess { prompt_id }` adds LLM post-processing
 * using the prompt with the given id (resolved against
 * `LlmPromptsStorage` at dispatch time \u2014 see T-A1.4). A `None`
 * prompt_id means "use the currently-active prompt" (UI default).
 */
export type ShortcutAction = { kind: "transcribe" } | { kind: "transcribe_post_process"; prompt_id?: string | null }
/**
 * One configurable hotkey row. `id` is a stable string key (locked by
 * the `stable_ids` test); `current_binding` is what the listener
 * registers. `default_binding` is shown next to a "reset" button in
 * the UI.
 */
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string; action?: ShortcutAction }
export type ThemeInfo = { id: string; name: string; description: string }
export type ThemeManifest = { manifest_version: number; id: string; name: string; description?: string; api_version: number; entry: string }
export type ThemeTestResult = { valid: boolean; warnings: string[]; errors: string[] }
/**
 * Transcription debug info.
 */
export type TranscriptionLog = { provider: string; model: string; language: string | null; duration_ms: number; text: string }
/**
 * Transcription result from API.
 */
export type TranscriptionResult = { text: string; language?: string | null; duration?: number | null }
/**
 * Voice Activity Detection settings.
 */
export type VadConfig = { enabled?: boolean; 
/**
 * VAD backend: `"none"` (no filtering, default), `"threshold"` (RMS-based),
 * or `"silero"` (Silero ONNX model).
 */
backend?: string; threshold?: number; 
/**
 * Consecutive voice frames required to trigger speech start.
 */
onset_frames?: number; 
/**
 * Silence frames tolerated before ending speech.
 */
hangover_frames?: number; 
/**
 * Past frames included when speech starts (captures word beginning).
 */
prefill_frames?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
