// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Get the current app configuration.
 */
async getConfig() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the app configuration.
 * SRP: Uses ConfigChangeHandler trait for change detection and response.
 */
async saveConfig(config: AppConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get transcription history.
 */
async getHistory(limit: number | null) : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all history entries.
 */
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all dictionary entries.
 */
async getDictionary() : Promise<Result<DictionaryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Main application configuration.
 * 
 * Groups:
 * - vad: Voice Activity Detection settings
 * - overlay: Recording overlay UI settings
 * - llm: LLM post-processing settings
 * - dictionary: Dictionary and learning settings
 */
export type AppConfig = { api_key?: string; model?: string; language?: string; hotkey?: string; auto_type?: boolean; auto_enter?: boolean; typing_delay?: number; notifications?: boolean; backend?: string; debug?: boolean; audio_device?: string; history_enabled?: boolean; history_days?: number; active_provider?: string; cloud_provider?: string; local_backend?: string; text_processing?: boolean; paste_shortcuts?: string; api_url_override?: string | null; vad?: VadConfig; overlay?: OverlayConfig; llm?: LlmConfig; dictionary?: DictionaryConfig }
/**
 * Dictionary and learning settings.
 */
export type DictionaryConfig = { path?: string; learning_mode?: string; learning_threshold?: number }
/**
 * Dictionary entry for frontend display.
 */
export type DictionaryEntry = { id: number; source: string; replacement: string }
/**
 * History entry for frontend display.
 */
export type HistoryEntry = { id: number; timestamp: string; text: string; language: string | null; duration: number | null }
/**
 * LLM post-processing settings.
 */
export type LlmConfig = { enabled?: boolean; provider?: string; api_url?: string; api_key?: string; model?: string; prompt?: string }
/**
 * Recording overlay settings.
 */
export type OverlayConfig = { enabled?: boolean; position?: string; size?: string; 
/**
 * Margin from screen edge in pixels. Can be negative to move overlay off-screen.
 */
margin?: number; 
/**
 * Audio level multiplier for waveform visualization (100-1000).
 * Higher = more sensitive for quiet microphones.
 */
audio_boost?: number; 
/**
 * Visualization theme name.
 */
theme?: string }
/**
 * Voice Activity Detection settings.
 */
export type VadConfig = { enabled?: boolean; threshold?: number; 
/**
 * Consecutive voice frames required to trigger speech start.
 */
onset_frames?: number; 
/**
 * Silence frames tolerated before ending speech.
 */
hangover_frames?: number; 
/**
 * Past frames included when speech starts (captures word beginning).
 */
prefill_frames?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
